#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the script since this line
#
# Your job name
#$ -N  lastz_repeats
#
# Send an email after the job has finished
#$ -m e
#$ -M lgfernandezluna@gmail.com
#
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh

# Add any modules you might require:
module load lastz/1.04.15

# Write your commands in the next line
#Run for every chromosome

lastz_32 chrN.fa [unmask,softmask=centromere_coordinates] --self --nomirror --step=10 -- maxwordcount=1 --masking=100 --strand=both --seed=match15 --twins=-10..15 --gfextend -- ydrop=5000	--interpolation=7000	--filter=identity:80	--filter=nmatch:160	 -- allocate:traceback=1.99G	--outputmasking=chrN_coordinates_masking	-- format=general:name1,start1,end1,strand1,length1,name2,start2+,end2+,strand2,length2,numbe r,identity,score > repeats_chrN.txt
