#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the script since this line
#
# Your job name
#$ -N  repeats5
#
# Send an email after the job has finished
#$ -m e
#$ -M lgfernandezluna@gmail.com
#
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh

# Add any modules you might require:
module load lastz/1.04.15

# Write your commands in the next line


lastz_32 ../chroms/xx20[unmask,softmask=sat_coordinates/chr21sat] --self --nomirror --step=10 --maxwordcount=1 --masking=100 --strand=minus --seed=match15 --twins=-10..15 --gfextend --ydrop=5000 --filter=identity:80 --filter=nmatch:160 --inner=5000 --allocate:traceback=1.99G --outputmasking=mask_21_file ‑‑format=general-:name1,start1,end1,strand1,length1,name2,start2+,end2+,strand2,length2,number,identity,score,blastid%,cgap > chr21inv.txt
 
awk '{ if(($5 >= 200) && ($10 >= 200) && ($15>=80)) print $0 }' chr21inv.txt > chr21inv_filtered.txt

lastz_32 ../chroms/xx21[unmask,softmask=sat_coordinates/chr22sat] --self --nomirror --step=10 --maxwordcount=1 --masking=100 --strand=minus --seed=match15 --twins=-10..15 --gfextend --ydrop=5000 --filter=identity:80 --filter=nmatch:160 --inner=5000 --allocate:traceback=1.99G --outputmasking=mask_22_file ‑‑format=general-:name1,start1,end1,strand1,length1,name2,start2+,end2+,strand2,length2,number,identity,score,blastid%,cgap > chr22inv.txt
 
awk '{ if(($5 >= 200) && ($10 >= 200) && ($15>=80)) print $0 }' chr22inv.txt > chr22inv_filtered.txt

lastz_32 ../chroms/xx23[unmask,softmask=sat_coordinates/chrYsat] --self --nomirror --step=10 --maxwordcount=1 --masking=100 --strand=minus --seed=match15 --twins=-10..15 --gfextend --ydrop=5000 --filter=identity:80 --filter=nmatch:160 --inner=5000 --allocate:traceback=1.99G --outputmasking=mask_Y_file ‑‑format=general-:name1,start1,end1,strand1,length1,name2,start2+,end2+,strand2,length2,number,identity,score,blastid%,cgap > chrYinv.txt
 
awk '{ if(($5 >= 200) && ($10 >= 200) && ($15>=80)) print $0 }' chrYinv.txt > chrYinv_filtered.txt

lastz_32 ../chroms/xx22[unmask,softmask=sat_coordinates/chrXsat] --self --nomirror --step=10 --maxwordcount=1 --masking=100 --strand=minus --seed=match15 --twins=-10..15 --gfextend --ydrop=5000 --filter=identity:80 --filter=nmatch:160 --inner=5000 --allocate:traceback=1.99G --outputmasking=mask_X_file ‑‑format=general-:name1,start1,end1,strand1,length1,name2,start2+,end2+,strand2,length2,number,identity,score,blastid%,cgap > chrXinv.txt
 
awk '{ if(($5 >= 200) && ($10 >= 200) && ($15>=80)) print $0 }' chrXinv.txt > chrXinv_filtered.txt
